keys:
  - &pc age1s846hz0u8c9clu6m8tdke8ve6v9cj3c3myuwp48c5kcwlm95dshqkc6jf9
  - &home-server age1tsveyqtg8823dmt6udkzx7thfl8ta4alr7dcckpsm5wux5784cpq98leg0
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *pc
      - *home-server
  - path_regex: secrets/secrets.env$
    key_groups:
    - age:
      - *pc
      - *home-server
