[[language]]
name = "rust"
language-server = { command = "rust-analyzer", environment = { "CARGO_TARGET_DIR" = "target/analyzer" } }
# auto-format = false

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[[language]]
name = "python"
indent = { tab-width = 4, unit = "4" }
comment-token = "#"

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "4" }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "4" }

[[language]]
name = "go"
auto-format = true

[[language]]
name = "arduino"
scope = "source.arduino"
grammar = "c"
language-server = { command = "arduino-language-server"}
file-types = ["ino", "arduino"]
roots = []
indent = { tab-width = 4, unit = "4" }

[[language]]
name = "hebi"
scope = "source.hebi"
file-types = ["hebi"]
roots = []
comment-token = "#"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
language-server = { command = "/home/salman/.cargo/bin/mdpls" }
config = { markdown.preview.auto = true, markdown.preview.browser = "firefox" }